// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: badge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const awardBadge = `-- name: AwardBadge :exec
INSERT INTO user_badges (user_id, badge_id)
VALUES ($1, $2)
ON CONFLICT (user_id, badge_id) DO NOTHING
`

type AwardBadgeParams struct {
	UserID  int32 `json:"user_id"`
	BadgeID int32 `json:"badge_id"`
}

func (q *Queries) AwardBadge(ctx context.Context, arg AwardBadgeParams) error {
	_, err := q.db.Exec(ctx, awardBadge, arg.UserID, arg.BadgeID)
	return err
}

const getAllBadgeDefinitions = `-- name: GetAllBadgeDefinitions :many
SELECT id, name, description, icon_key, criteria_type, criteria_value, created_at FROM badge_definitions
ORDER BY id
`

func (q *Queries) GetAllBadgeDefinitions(ctx context.Context) ([]BadgeDefinition, error) {
	rows, err := q.db.Query(ctx, getAllBadgeDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BadgeDefinition{}
	for rows.Next() {
		var i BadgeDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconKey,
			&i.CriteriaType,
			&i.CriteriaValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBadgeCount = `-- name: GetUserBadgeCount :one
SELECT COUNT(*) FROM user_badges
WHERE user_id = $1
`

func (q *Queries) GetUserBadgeCount(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUserBadgeCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserBadges = `-- name: GetUserBadges :many
SELECT
    bd.id,
    bd.name,
    bd.description,
    bd.icon_key,
    bd.criteria_type,
    bd.criteria_value,
    ub.earned_at
FROM user_badges ub
JOIN badge_definitions bd ON bd.id = ub.badge_id
WHERE ub.user_id = $1
ORDER BY ub.earned_at DESC
`

type GetUserBadgesRow struct {
	ID            int32            `json:"id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	IconKey       *string          `json:"icon_key"`
	CriteriaType  string           `json:"criteria_type"`
	CriteriaValue int32            `json:"criteria_value"`
	EarnedAt      pgtype.Timestamp `json:"earned_at"`
}

func (q *Queries) GetUserBadges(ctx context.Context, userID int32) ([]GetUserBadgesRow, error) {
	rows, err := q.db.Query(ctx, getUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserBadgesRow{}
	for rows.Next() {
		var i GetUserBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconKey,
			&i.CriteriaType,
			&i.CriteriaValue,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
