// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          int32            `json:"id"`
	UserID      int32            `json:"user_id"`
	Title       string           `json:"title"`
	CompanyName *string          `json:"company_name"`
	Notes       *string          `json:"notes"`
	Link        *string          `json:"link"`
	Location    *string          `json:"location"`
	Platform    *string          `json:"platform"`
	DateApplied pgtype.Timestamp `json:"date_applied"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RefreshToken struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           int32            `json:"id"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	Email        string           `json:"email"`
	PhoneNumber  *string          `json:"phone_number"`
	PasswordHash *string          `json:"password_hash"`
	LinkedinID   *string          `json:"linkedin_id"`
	IsActive     *bool            `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type UserProfile struct {
	ID              int32            `json:"id"`
	UserID          int32            `json:"user_id"`
	Cv              []byte           `json:"cv"`
	FullName        *string          `json:"full_name"`
	CurrentJob      *string          `json:"current_job"`
	ExperienceLevel *string          `json:"experience_level"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}
