// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProgressSummary = `-- name: GetProgressSummary :one
SELECT
    COALESCE(SUM(total_focus_seconds), 0)::bigint AS total_focus_seconds,
    COALESCE(SUM(sessions_completed), 0)::bigint  AS sessions_completed,
    COUNT(DISTINCT date)::bigint                  AS days_active
FROM daily_progress
WHERE user_id = $1
  AND date BETWEEN $2 AND $3
`

type GetProgressSummaryParams struct {
	UserID int32       `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetProgressSummaryRow struct {
	TotalFocusSeconds int64 `json:"total_focus_seconds"`
	SessionsCompleted int64 `json:"sessions_completed"`
	DaysActive        int64 `json:"days_active"`
}

func (q *Queries) GetProgressSummary(ctx context.Context, arg GetProgressSummaryParams) (GetProgressSummaryRow, error) {
	row := q.db.QueryRow(ctx, getProgressSummary, arg.UserID, arg.Date, arg.Date_2)
	var i GetProgressSummaryRow
	err := row.Scan(&i.TotalFocusSeconds, &i.SessionsCompleted, &i.DaysActive)
	return i, err
}

const upsertDailyProgress = `-- name: UpsertDailyProgress :exec
INSERT INTO daily_progress (
    user_id,
    date,
    total_focus_seconds,
    sessions_completed
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id, date) DO UPDATE SET
    total_focus_seconds = daily_progress.total_focus_seconds + EXCLUDED.total_focus_seconds,
    sessions_completed  = daily_progress.sessions_completed  + EXCLUDED.sessions_completed
`

type UpsertDailyProgressParams struct {
	UserID            int32       `json:"user_id"`
	Date              pgtype.Date `json:"date"`
	TotalFocusSeconds int32       `json:"total_focus_seconds"`
	SessionsCompleted int32       `json:"sessions_completed"`
}

func (q *Queries) UpsertDailyProgress(ctx context.Context, arg UpsertDailyProgressParams) error {
	_, err := q.db.Exec(ctx, upsertDailyProgress,
		arg.UserID,
		arg.Date,
		arg.TotalFocusSeconds,
		arg.SessionsCompleted,
	)
	return err
}
