// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeactivateUser(ctx context.Context, id int32) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteJobByID(ctx context.Context, id int32) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteUserRefreshTokens(ctx context.Context, userID int32) error
	GetJobByID(ctx context.Context, id int32) (Job, error)
	GetJobs(ctx context.Context, userID int32) ([]Job, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserProfileByUserID(ctx context.Context, userID int32) (UserProfile, error)
	UpdateJobByID(ctx context.Context, arg UpdateJobByIDParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
	UploadUserCV(ctx context.Context, arg UploadUserCVParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
