// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFocusSession = `-- name: CreateFocusSession :one
INSERT INTO focus_sessions (
    user_id,
    duration_seconds,
    status
) VALUES (
    $1, $2, 'active'
) RETURNING id, user_id, duration_seconds, elapsed_seconds, status, started_at, ended_at, created_at, updated_at
`

type CreateFocusSessionParams struct {
	UserID          int32 `json:"user_id"`
	DurationSeconds int32 `json:"duration_seconds"`
}

func (q *Queries) CreateFocusSession(ctx context.Context, arg CreateFocusSessionParams) (FocusSession, error) {
	row := q.db.QueryRow(ctx, createFocusSession, arg.UserID, arg.DurationSeconds)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DurationSeconds,
		&i.ElapsedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, duration_seconds, elapsed_seconds, status, started_at, ended_at, created_at, updated_at FROM focus_sessions
WHERE user_id = $1 AND status IN ('active', 'paused')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSession(ctx context.Context, userID int32) (FocusSession, error) {
	row := q.db.QueryRow(ctx, getActiveSession, userID)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DurationSeconds,
		&i.ElapsedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFocusSessionByID = `-- name: GetFocusSessionByID :one
SELECT id, user_id, duration_seconds, elapsed_seconds, status, started_at, ended_at, created_at, updated_at FROM focus_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFocusSessionByID(ctx context.Context, id int32) (FocusSession, error) {
	row := q.db.QueryRow(ctx, getFocusSessionByID, id)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DurationSeconds,
		&i.ElapsedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionHistory = `-- name: GetUserSessionHistory :many
SELECT id, user_id, duration_seconds, elapsed_seconds, status, started_at, ended_at, created_at, updated_at FROM focus_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type GetUserSessionHistoryParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUserSessionHistory(ctx context.Context, arg GetUserSessionHistoryParams) ([]FocusSession, error) {
	rows, err := q.db.Query(ctx, getUserSessionHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FocusSession{}
	for rows.Next() {
		var i FocusSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DurationSeconds,
			&i.ElapsedSeconds,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFocusSession = `-- name: UpdateFocusSession :one
UPDATE focus_sessions
SET
    elapsed_seconds = $2,
    status = $3,
    ended_at = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, duration_seconds, elapsed_seconds, status, started_at, ended_at, created_at, updated_at
`

type UpdateFocusSessionParams struct {
	ID             int32            `json:"id"`
	ElapsedSeconds int32            `json:"elapsed_seconds"`
	Status         string           `json:"status"`
	EndedAt        pgtype.Timestamp `json:"ended_at"`
}

func (q *Queries) UpdateFocusSession(ctx context.Context, arg UpdateFocusSessionParams) (FocusSession, error) {
	row := q.db.QueryRow(ctx, updateFocusSession,
		arg.ID,
		arg.ElapsedSeconds,
		arg.Status,
		arg.EndedAt,
	)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DurationSeconds,
		&i.ElapsedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
