// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: streaks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStreak = `-- name: GetStreak :one
SELECT id, user_id, current_streak, longest_streak, last_session_date, updated_at FROM streaks
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetStreak(ctx context.Context, userID int32) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreak, userID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastSessionDate,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStreak = `-- name: UpsertStreak :one
INSERT INTO streaks (
    user_id,
    current_streak,
    longest_streak,
    last_session_date,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW()
) ON CONFLICT (user_id) DO UPDATE SET
    current_streak    = EXCLUDED.current_streak,
    longest_streak    = GREATEST(streaks.longest_streak, EXCLUDED.longest_streak),
    last_session_date = EXCLUDED.last_session_date,
    updated_at        = NOW()
RETURNING id, user_id, current_streak, longest_streak, last_session_date, updated_at
`

type UpsertStreakParams struct {
	UserID          int32       `json:"user_id"`
	CurrentStreak   int32       `json:"current_streak"`
	LongestStreak   int32       `json:"longest_streak"`
	LastSessionDate pgtype.Date `json:"last_session_date"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) (Streak, error) {
	row := q.db.QueryRow(ctx, upsertStreak,
		arg.UserID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastSessionDate,
	)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastSessionDate,
		&i.UpdatedAt,
	)
	return i, err
}
