// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profile.sql

package db

import (
	"context"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profile (
    user_id,
    full_name,
    current_job,
    experience_level
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, cv, full_name, current_job, experience_level, updated_at
`

type CreateUserProfileParams struct {
	UserID          int32   `json:"user_id"`
	FullName        *string `json:"full_name"`
	CurrentJob      *string `json:"current_job"`
	ExperienceLevel *string `json:"experience_level"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.FullName,
		arg.CurrentJob,
		arg.ExperienceLevel,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Cv,
		&i.FullName,
		&i.CurrentJob,
		&i.ExperienceLevel,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT id, user_id, cv, full_name, current_job, experience_level, updated_at FROM user_profile
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID int32) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Cv,
		&i.FullName,
		&i.CurrentJob,
		&i.ExperienceLevel,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profile
SET
    full_name = CASE WHEN $2::text IS NOT NULL THEN $2 ELSE full_name END,
    current_job = CASE WHEN $3::text IS NOT NULL THEN $3 ELSE current_job END,
    experience_level = CASE WHEN $4::text IS NOT NULL THEN $4 ELSE experience_level END,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, cv, full_name, current_job, experience_level, updated_at
`

type UpdateUserProfileParams struct {
	UserID          int32   `json:"user_id"`
	FullName        *string `json:"full_name"`
	CurrentJob      *string `json:"current_job"`
	ExperienceLevel *string `json:"experience_level"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.FullName,
		arg.CurrentJob,
		arg.ExperienceLevel,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Cv,
		&i.FullName,
		&i.CurrentJob,
		&i.ExperienceLevel,
		&i.UpdatedAt,
	)
	return i, err
}

const uploadUserCV = `-- name: UploadUserCV :one
UPDATE user_profile
SET
    cv = $2,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, cv, full_name, current_job, experience_level, updated_at
`

type UploadUserCVParams struct {
	UserID int32  `json:"user_id"`
	Cv     []byte `json:"cv"`
}

func (q *Queries) UploadUserCV(ctx context.Context, arg UploadUserCVParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, uploadUserCV, arg.UserID, arg.Cv)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Cv,
		&i.FullName,
		&i.CurrentJob,
		&i.ExperienceLevel,
		&i.UpdatedAt,
	)
	return i, err
}
