package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"

	"aiki/internal/config"
	"aiki/internal/database"
	"aiki/internal/handler"
	"aiki/internal/middleware"
	"aiki/internal/pkg/jwt"
	"aiki/internal/pkg/validator"
	"aiki/internal/repository"
	"aiki/internal/router"
	"aiki/internal/service"

	_ "aiki/docs" // generated by swag init

	"github.com/labstack/echo/v4"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title           Aiki API
// @version         1.0
// @description     Backend API for Aiki — focus sessions, job tracking, streaks and badges.

// @contact.name    Aiki Support
// @contact.email   support@aiki.app

// @host            localhost:8080
// @BasePath        /api/v1

// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
// @description     Type "Bearer" followed by your access token. Example: "Bearer eyJhbGc..."

func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Initialize database connection
	db, err := database.NewPostgresPool(&cfg.Database)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()
	log.Println("✓ Database connection established")

	// Initialize Redis client
	redis, err := database.NewRedisClient(&cfg.Redis)
	if err != nil {
		log.Fatalf("Failed to connect to Redis: %v", err)
	}
	defer redis.Close()
	log.Println("✓ Redis connection established")

	// Initialize JWT manager
	jwtManager := jwt.NewManager(
		cfg.JWT.Secret,
		cfg.JWT.AccessExpiry,
		cfg.JWT.RefreshExpiry,
	)

	// Initialize repositories
	userRepo := repository.NewUserRepository(db)
	jobRepo := repository.NewJobRepository(db)
	homeRepo := repository.NewHomeRepository(db)

	// Initialize services
	authService := service.NewAuthService(userRepo, jwtManager)
	userService := service.NewUserService(userRepo)
	jobService := service.NewJobService(jobRepo)
	homeService := service.NewHomeService(homeRepo)

	// Initialize Echo
	e := echo.New()
	e.HideBanner = true
	e.Validator = validator.New()

	// Global middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.Use(middleware.CORS())

	// Swagger UI (available at /swagger/index.html)
	e.GET("/swagger/*", echo.WrapHandler(httpSwagger.WrapHandler))

	// Initialize handlers
	authHandler := handler.NewAuthHandler(authService, e.Validator, redis)
	userHandler := handler.NewUserHandler(userService, e.Validator)
	jobHandler := handler.NewJobHandler(jobService, e.Validator)
	homeHandler := handler.NewHomeHandler(homeService, e.Validator)

	// Setup routes
	router.Setup(e, authHandler, userHandler, jobHandler, homeHandler, jwtManager)

	// Start server
	serverAddr := fmt.Sprintf(":%s", cfg.Server.Port)
	go func() {
		log.Printf("✓ Server starting on %s", serverAddr)
		log.Printf("✓ Swagger UI available at http://localhost%s/swagger/index.html", serverAddr)
		if err := e.Start(serverAddr); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Failed to start server: %v", err)
		}
	}()

	// Graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt)
	<-quit

	log.Println("Shutting down server...")

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := e.Shutdown(ctx); err != nil {
		log.Fatalf("Server forced to shutdown: %v", err)
	}

	log.Println("Server exited")
}
